import { 
  User, 
  ExpenseSource, 
  PaymentType, 
  AccountTitle, 
  Person, 
  Invoice, 
  AuditLog, 
  AppSettings, 
  Notification, 
  RecurringInvoice, 
  RecurringInvoiceFrequency,
  EmailLog
} from '../types';
import { generateSealCode, generateReferenceCode, numberToWords } from './utils';

// Mock DB Initial Data
const initialSettings: AppSettings = {
  theme: 'light',
  accentColor: 'blue',
  invoicePrefix: 'INV-WAL-MIS',
  invoicePadding: 6,
  backupReminderFrequency: 'weekly',
  lastBackupDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days ago to demonstrate reminder
  branding: {
    companyName: 'Walton Hi-Tech Industries PLC',
    companySubtitle: 'MISCELLANEOUS FUND',
    companyTagline: 'Excellence in Enterprise Financial Governance',
    companyAddress: 'Chandra, Gazipur / Corporate HQ: Plot-1088, Block-I, Sabrina Sobhan Road, Dhaka-1229',
    companyPhone: '+880 9606-555555',
    companyEmail: 'accounts@waltonbd.com',
    companyTaxId: 'BIN: 000129482-0101 / TIN: 719284920194',
    companyWebsite: 'https://waltonbd.com',
    logoInitials: 'MF',
    themeColor: '#1e3a8a', // Corporate Blue
    templateStyle: 'modern',
    showWatermark: true,
    showQrCode: true,
    showSignatures: true,
    showTaxBin: true,
    showReviewNotes: true,
    footerTerms: 'This expenditure voucher is an authorized financial document generated by Third Eye ERP. Retain for tax audit & verification.'
  }
};

const initialUsers: User[] = [
  { id: '1', name: 'Super Admin', email: 'admin@thirdeye.com', role: 'Super Admin', isActive: true },
  { id: '2', name: 'Regular Pro', email: 'pro@thirdeye.com', role: 'Pro', isActive: true },
];

const initialExpenseSources: ExpenseSource[] = [
  { id: '1', name: 'WALTON HI-TECH INDUSTRIES PLC (WFR)', description: 'Product- Refrigerator', address: 'Chandra, Gazipur', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '2', name: 'WALTON DIGITECH INDUSTRIES LIMITED (COMPUTER)', description: 'Product- Computer', address: 'Chandra, Gazipur', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '3', name: 'Star Tech & Engineering Ltd', description: 'IT Equipment & Accessories', address: 'Dhanmondi, Dhaka', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '4', name: 'Dhaka Electric Supply Company (DESCO)', description: 'Utility Power Provider', address: 'Nikunja-2, Khilkhet, Dhaka', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '5', name: 'Amazon Web Services (AWS)', description: 'Cloud Infrastructure & Servers', address: 'Seattle, WA, USA', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '6', name: 'Apex Property Management', description: 'Corporate Office Lease', address: 'Gulshan-1, Dhaka', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
];

const initialPaymentTypes: PaymentType[] = [
  { id: '1', name: 'DRAWINGS-COMMON', description: 'From Other Legal Entity', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '2', name: 'PERSONAL EXPENSE', description: 'From DMD Sir Miscellaneous Fund', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '3', name: 'UTILITY & INFRASTRUCTURE', description: 'Operational utilities & cloud expenses', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '4', name: 'OFFICE SUPPLIES & HARDWARE', description: 'IT hardware and office essentials', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '5', name: 'SUBSCRIPTIONS & LICENSES', description: 'Recurring software and services', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
];

const initialAccountTitles: AccountTitle[] = [
  { id: '1', name: 'General Reserve', description: 'Main reserve fund', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '2', name: 'Common Fund', description: 'BOD Common Fund', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '3', name: 'IT Infrastructure Fund', description: 'Cloud, Server & Software budget', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '4', name: 'Administrative Overhead', description: 'Facility and operational expenses', isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
];

const initialPeople: Person[] = [
  { id: '1', name: 'Sazzad Kabir', description: 'Employee', officeId: '7130', designation: 'Manager', isReceivedBy: true, isPreparedBy: true, isVerifiedBy: true, isApprovedBy: false, isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '2', name: 'Nazrul Islam Sarker', description: 'Employee', officeId: '303', designation: 'AMD', isReceivedBy: true, isPreparedBy: false, isVerifiedBy: true, isApprovedBy: true, isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '3', name: 'Abul Kalam', description: 'Employee', officeId: '1071', designation: 'Bodyguard', isReceivedBy: true, isPreparedBy: false, isVerifiedBy: false, isApprovedBy: false, isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
  { id: '4', name: 'Tanvir Hossain', description: 'Employee', officeId: '4021', designation: 'Lead Systems Architect', isReceivedBy: true, isPreparedBy: true, isVerifiedBy: true, isApprovedBy: false, isActive: true, createdBy: '1', createdAt: new Date().toISOString() },
];

// Helper to compute next billing date given frequency and billing day
export const computeNextBillingDate = (frequency: RecurringInvoiceFrequency, billingDay: number, fromDate: Date = new Date()): string => {
  const next = new Date(fromDate);
  const day = Math.min(Math.max(billingDay || 1, 1), 28); // Cap safely for all months
  
  if (frequency === 'Weekly') {
    next.setDate(next.getDate() + 7);
  } else if (frequency === 'Monthly') {
    next.setMonth(next.getMonth() + 1);
    next.setDate(day);
  } else if (frequency === 'Quarterly') {
    next.setMonth(next.getMonth() + 3);
    next.setDate(day);
  } else if (frequency === 'Yearly') {
    next.setFullYear(next.getFullYear() + 1);
    next.setDate(day);
  }
  return next.toISOString().split('T')[0];
};

const initialRecurringInvoices: RecurringInvoice[] = [
  {
    id: 'rec-1',
    title: 'AWS Enterprise Cloud Hosting & EC2 Cluster',
    expenseSourceId: '5',
    paymentTypeId: '3',
    accountTitleId: '3',
    purpose: 'Monthly cloud servers, database hosting, and high availability CDN subscription',
    amount: 145000,
    frequency: 'Monthly',
    billingDay: 1,
    startDate: '2026-01-01',
    nextBillingDate: '2026-09-01',
    status: 'Active',
    autoGenerate: true,
    preparedById: '4',
    verifiedById: '1',
    approvedById: '2',
    receivedById: '1',
    remarks: 'Auto-recurs on 1st of every month. Vendor invoice attached automatically.',
    lastGeneratedDate: '2026-08-01',
    createdBy: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: 'rec-2',
    title: 'Corporate Headquarters Office Lease & Maintenance',
    expenseSourceId: '6',
    paymentTypeId: '1',
    accountTitleId: '4',
    purpose: 'Quarterly office lease agreement payment and building maintenance fee',
    amount: 450000,
    frequency: 'Quarterly',
    billingDay: 15,
    startDate: '2026-01-15',
    nextBillingDate: '2026-10-15',
    status: 'Active',
    autoGenerate: false,
    preparedById: '1',
    verifiedById: '1',
    approvedById: '2',
    receivedById: '1',
    remarks: 'Approved per BOD lease agreement 2026-Q1.',
    lastGeneratedDate: '2026-07-15',
    createdBy: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: 'rec-3',
    title: 'Dedicated Fiber Internet & Security Leased Line',
    expenseSourceId: '3',
    paymentTypeId: '5',
    accountTitleId: '3',
    purpose: 'High-speed 1Gbps dedicated optical link for ERP servers',
    amount: 65000,
    frequency: 'Monthly',
    billingDay: 10,
    startDate: '2026-02-10',
    nextBillingDate: '2026-09-10',
    status: 'Active',
    autoGenerate: true,
    preparedById: '4',
    verifiedById: '1',
    approvedById: '2',
    receivedById: '1',
    remarks: 'Monthly recurring utility subscription.',
    lastGeneratedDate: '2026-08-10',
    createdBy: '1',
    createdAt: new Date().toISOString()
  }
];

// Helper to generate seed historical invoices for rich chart visualization
const generateSeedInvoices = (): Invoice[] => {
  const seedInvoices: Invoice[] = [];
  const now = new Date();
  
  const sampleItems = [
    { src: '1', pay: '1', acc: '1', pur: 'Factory refrigeration components procurement', amt: 320000 },
    { src: '2', pay: '4', acc: '3', pur: 'Workstation computers and monitor upgrades', amt: 185000 },
    { src: '3', pay: '4', acc: '3', pur: 'Network switches and patch cords for server rack', amt: 75000 },
    { src: '4', pay: '3', acc: '4', pur: 'Monthly electricity and power utility consumption', amt: 142000 },
    { src: '5', pay: '3', acc: '3', pur: 'AWS Cloud computing, backups and storage services', amt: 135000 },
    { src: '6', pay: '1', acc: '4', pur: 'Office facility lease advance and service charge', amt: 210000 },
  ];

  // Distribute over last 6 months (0 to 5 months ago)
  for (let m = 5; m >= 0; m--) {
    const d = new Date(now.getFullYear(), now.getMonth() - m, 12);
    const monthStr = d.toLocaleString('default', { month: 'short' }).toUpperCase();
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    const dateStr = `${year}${month}${day}`;

    sampleItems.forEach((item, idx) => {
      // Small variation in amount
      const variation = (idx % 2 === 0 ? 1 : -1) * (m * 4500) + (idx * 3200);
      const finalAmt = Math.max(25000, item.amt + variation);
      const invDate = new Date(year, d.getMonth(), 5 + idx * 3).toISOString();
      const seqStr = String(idx + 1 + m * 6).padStart(6, '0');

      seedInvoices.push({
        id: `inv-seed-${m}-${idx}`,
        invoiceNumber: `INV-WAL-MIS-${dateStr}-${seqStr}`,
        date: invDate,
        expenseSourceId: item.src,
        paymentTypeId: item.pay,
        accountTitleId: item.acc,
        purpose: `${item.pur} - ${monthStr} ${year}`,
        amount: finalAmt,
        amountInWords: numberToWords(finalAmt),
        preparedById: '1',
        verifiedById: '1',
        approvedById: '2',
        receivedById: '1',
        status: 'Approved',
        sealCode: generateSealCode(),
        referenceCode: generateReferenceCode(),
        createdBy: '1',
        createdAt: invDate,
        updatedAt: invDate,
        remarks: 'Processed and reconciled in accordance with financial policies.'
      });
    });
  }

  return seedInvoices;
};

// Helper to init DB
const initDB = () => {
  const existingInvoices = localStorage.getItem('te_invoices');
  const parsedInvoices: Invoice[] = existingInvoices ? JSON.parse(existingInvoices) : [];

  if (!localStorage.getItem('thirdeye_db_initialized') || parsedInvoices.length < 5) {
    localStorage.setItem('te_users', JSON.stringify(initialUsers));
    localStorage.setItem('te_expense_sources', JSON.stringify(initialExpenseSources));
    localStorage.setItem('te_payment_types', JSON.stringify(initialPaymentTypes));
    localStorage.setItem('te_account_titles', JSON.stringify(initialAccountTitles));
    localStorage.setItem('te_people', JSON.stringify(initialPeople));
    
    // Seed invoices if none exist or only minimal
    const invoicesToSave = parsedInvoices.length >= 5 ? parsedInvoices : generateSeedInvoices();
    localStorage.setItem('te_invoices', JSON.stringify(invoicesToSave));
    
    localStorage.setItem('te_recurring_invoices', JSON.stringify(initialRecurringInvoices));
    localStorage.setItem('te_email_logs', JSON.stringify([]));
    localStorage.setItem('te_audit_logs', JSON.stringify([]));
    localStorage.setItem('te_notifications', JSON.stringify([
      { id: '1', userId: '1', title: 'System Initialization', message: 'Welcome to THIRD EYE ERP. Recurring invoices and automated schedules ready.', read: false, createdAt: new Date().toISOString() }
    ]));
    
    // Ensure settings has backup reminders
    const savedSettings = localStorage.getItem('te_settings');
    if (!savedSettings) {
      localStorage.setItem('te_settings', JSON.stringify(initialSettings));
    } else {
      const merged = { ...initialSettings, ...JSON.parse(savedSettings) };
      localStorage.setItem('te_settings', JSON.stringify(merged));
    }
    
    localStorage.setItem('thirdeye_db_initialized', 'true');
  } else {
    // Ensure recurring invoices table exists
    if (!localStorage.getItem('te_recurring_invoices')) {
      localStorage.setItem('te_recurring_invoices', JSON.stringify(initialRecurringInvoices));
    }
    // Ensure settings has branding
    const savedSettings = localStorage.getItem('te_settings');
    if (savedSettings) {
      const parsed = JSON.parse(savedSettings);
      if (!parsed.branding) {
        localStorage.setItem('te_settings', JSON.stringify({ ...initialSettings, ...parsed, branding: initialSettings.branding }));
      }
    }
  }
};

initDB();

// Mock Delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));


async function computeHash(message: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

export const db = {
  users: {
    getAll: async (): Promise<User[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_users') || '[]'); },
    getById: async (id: string): Promise<User | undefined> => {
      const users = await db.users.getAll();
      return users.find(u => u.id === id);
    },
    save: async (data: User) => {
      const all = await db.users.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_users', JSON.stringify(all));
    }
  },
  expenseSources: {
    getAll: async (): Promise<ExpenseSource[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_expense_sources') || '[]'); },
    save: async (data: ExpenseSource) => {
      const all = await db.expenseSources.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_expense_sources', JSON.stringify(all));
    },
    saveBulk: async (items: ExpenseSource[]) => {
      const all = await db.expenseSources.getAll();
      for (const item of items) {
        const existing = all.findIndex(i => i.id === item.id || i.name.toLowerCase() === item.name.toLowerCase());
        if (existing >= 0) all[existing] = { ...all[existing], ...item };
        else all.push(item);
      }
      localStorage.setItem('te_expense_sources', JSON.stringify(all));
    },
    delete: async (id: string) => {
      const all = await db.expenseSources.getAll();
      localStorage.setItem('te_expense_sources', JSON.stringify(all.filter(i => i.id !== id)));
    }
  },
  paymentTypes: {
    getAll: async (): Promise<PaymentType[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_payment_types') || '[]'); },
    save: async (data: PaymentType) => {
      const all = await db.paymentTypes.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_payment_types', JSON.stringify(all));
    },
    saveBulk: async (items: PaymentType[]) => {
      const all = await db.paymentTypes.getAll();
      for (const item of items) {
        const existing = all.findIndex(i => i.id === item.id || i.name.toLowerCase() === item.name.toLowerCase());
        if (existing >= 0) all[existing] = { ...all[existing], ...item };
        else all.push(item);
      }
      localStorage.setItem('te_payment_types', JSON.stringify(all));
    },
    delete: async (id: string) => {
      const all = await db.paymentTypes.getAll();
      localStorage.setItem('te_payment_types', JSON.stringify(all.filter(i => i.id !== id)));
    }
  },
  accountTitles: {
    getAll: async (): Promise<AccountTitle[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_account_titles') || '[]'); },
    save: async (data: AccountTitle) => {
      const all = await db.accountTitles.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_account_titles', JSON.stringify(all));
    },
    saveBulk: async (items: AccountTitle[]) => {
      const all = await db.accountTitles.getAll();
      for (const item of items) {
        const existing = all.findIndex(i => i.id === item.id || i.name.toLowerCase() === item.name.toLowerCase());
        if (existing >= 0) all[existing] = { ...all[existing], ...item };
        else all.push(item);
      }
      localStorage.setItem('te_account_titles', JSON.stringify(all));
    },
    delete: async (id: string) => {
      const all = await db.accountTitles.getAll();
      localStorage.setItem('te_account_titles', JSON.stringify(all.filter(i => i.id !== id)));
    }
  },
  people: {
    getAll: async (): Promise<Person[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_people') || '[]'); },
    save: async (data: Person) => {
      const all = await db.people.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_people', JSON.stringify(all));
    },
    saveBulk: async (items: Person[]) => {
      const all = await db.people.getAll();
      for (const item of items) {
        const existing = all.findIndex(i => i.id === item.id || i.name.toLowerCase() === item.name.toLowerCase());
        if (existing >= 0) all[existing] = { ...all[existing], ...item };
        else all.push(item);
      }
      localStorage.setItem('te_people', JSON.stringify(all));
    },
    delete: async (id: string) => {
      const all = await db.people.getAll();
      localStorage.setItem('te_people', JSON.stringify(all.filter(i => i.id !== id)));
    }
  },
  invoices: {
    getAll: async (): Promise<Invoice[]> => { await delay(100); return JSON.parse(localStorage.getItem('te_invoices') || '[]'); },
    getById: async (id: string): Promise<Invoice | undefined> => {
      const all = await db.invoices.getAll();
      return all.find(i => i.id === id);
    },
    save: async (data: Invoice) => {
      const all = await db.invoices.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      
      const nowIso = new Date().toISOString();
      const statusKey = `${data.status.toLowerCase()}At`;
      
      const timestamps = data.statusTimestamps || {};
      if (!timestamps[statusKey]) {
        timestamps[statusKey] = nowIso;
      }

      const history = data.approvalHistory || [
        {
          id: crypto.randomUUID(),
          status: data.status,
          timestamp: data.createdAt || nowIso,
          actorId: data.createdBy || 'sys',
          actorName: 'Invoice Originator',
          note: data.remarks || `Initial status recorded as ${data.status}`
        }
      ];

      const invoiceWithMeta: Invoice = {
        ...data,
        statusTimestamps: timestamps,
        approvalHistory: history
      };

      if (existing >= 0) all[existing] = invoiceWithMeta; else all.push(invoiceWithMeta);
      localStorage.setItem('te_invoices', JSON.stringify(all));
    },
    updateStatus: async (id: string, status: Invoice['status'], actorId: string, reviewRemarks?: string, actorName?: string): Promise<Invoice> => {
      const all = await db.invoices.getAll();
      const idx = all.findIndex(i => i.id === id);
      if (idx === -1) throw new Error('Invoice not found');
      
      const inv = all[idx];
      const previousStatus = inv.status;
      const nowIso = new Date().toISOString();

      // Look up actor name if not provided
      let resolvedActorName = actorName;
      if (!resolvedActorName) {
        const users: User[] = JSON.parse(localStorage.getItem('te_users') || '[]');
        const user = users.find(u => u.id === actorId);
        if (user) {
          resolvedActorName = `${user.name} (${user.role})`;
        } else {
          const people: Person[] = JSON.parse(localStorage.getItem('te_people') || '[]');
          const person = people.find(p => p.id === actorId);
          resolvedActorName = person?.name || (actorId === 'sys' ? 'System Administrator' : 'Authorized Approver');
        }
      }

      // Update specific status timestamp
      const statusTimestamps = { ...(inv.statusTimestamps || {}) };
      const statusKey = `${status.toLowerCase()}At`;
      statusTimestamps[statusKey] = nowIso;
      if (status === 'Pending') statusTimestamps.pendingAt = nowIso;
      if (status === 'Approved') statusTimestamps.approvedAt = nowIso;
      if (status === 'Rejected') statusTimestamps.rejectedAt = nowIso;
      if (status === 'Returned') statusTimestamps.returnedAt = nowIso;
      if (status === 'Received') statusTimestamps.receivedAt = nowIso;

      // Append to approval history trail
      const existingHistory = inv.approvalHistory || [];
      const newHistoryEntry = {
        id: crypto.randomUUID(),
        status,
        timestamp: nowIso,
        actorId,
        actorName: resolvedActorName,
        note: reviewRemarks || `Workflow moved to ${status}`
      };

      const updated: Invoice = {
        ...inv,
        status,
        statusTimestamps,
        approvalHistory: [...existingHistory, newHistoryEntry],
        reviewRemarks: reviewRemarks !== undefined ? reviewRemarks : inv.reviewRemarks,
        reviewedById: actorId,
        reviewedAt: nowIso,
        updatedAt: nowIso
      };

      all[idx] = updated;
      localStorage.setItem('te_invoices', JSON.stringify(all));

      // Audit Log
      await db.auditLogs.add(
        actorId,
        `Workflow Status Change: ${previousStatus} -> ${status}`,
        'Invoice Approval Workflow',
        id,
        `Invoice ${inv.invoiceNumber} status set to "${status}" at ${new Date(nowIso).toLocaleTimeString()}. Reviewer: ${resolvedActorName}. Remarks: ${reviewRemarks || 'None'}`
      );

      // Trigger notification to the invoice creator / preparer
      if (inv.createdBy && inv.createdBy !== actorId) {
        await db.notifications.add({
          userId: inv.createdBy,
          title: `Invoice ${status}`,
          message: `Your invoice ${inv.invoiceNumber} (${inv.purpose}) has been changed from ${previousStatus} to ${status} by ${resolvedActorName}.${reviewRemarks ? ` Note: "${reviewRemarks}"` : ''}`
        });
      }

      return updated;
    },
    delete: async (id: string, actorId: string = '1') => {
      const all = await db.invoices.getAll();
      const target = all.find(i => i.id === id);
      localStorage.setItem('te_invoices', JSON.stringify(all.filter(i => i.id !== id)));
      
      if (target) {
        await db.auditLogs.add(
          actorId,
          'Delete Invoice',
          'Invoice',
          id,
          `Permanently deleted invoice ${target.invoiceNumber} (Amount: ${target.amount}, Purpose: "${target.purpose}")`
        );
      }
    },
    generateInvoiceNumber: async (): Promise<string> => {
      const all = await db.invoices.getAll();
      const settings = await db.settings.get();
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      const dateStr = `${year}${month}${day}`;
      
      const currentMonthInvoices = all.filter(i => {
        const d = new Date(i.createdAt || i.date);
        return d.getFullYear() === year && d.getMonth() === date.getMonth();
      });
      
      const seq = currentMonthInvoices.length + 1;
      const paddedSeq = seq.toString().padStart(settings.invoicePadding || 6, '0');
      
      return `${settings.invoicePrefix || 'INV-WAL-MIS'}-${dateStr}-${paddedSeq}`;
    }
  },
  recurringInvoices: {
    getAll: async (): Promise<RecurringInvoice[]> => {
      await delay(50);
      return JSON.parse(localStorage.getItem('te_recurring_invoices') || '[]');
    },
    getById: async (id: string): Promise<RecurringInvoice | undefined> => {
      const all = await db.recurringInvoices.getAll();
      return all.find(r => r.id === id);
    },
    save: async (data: RecurringInvoice) => {
      const all = await db.recurringInvoices.getAll();
      const existing = all.findIndex(i => i.id === data.id);
      if (existing >= 0) all[existing] = data; else all.push(data);
      localStorage.setItem('te_recurring_invoices', JSON.stringify(all));
    },
    delete: async (id: string) => {
      const all = await db.recurringInvoices.getAll();
      localStorage.setItem('te_recurring_invoices', JSON.stringify(all.filter(i => i.id !== id)));
    },
    generateNow: async (recurringId: string, actorId: string): Promise<Invoice> => {
      const rec = await db.recurringInvoices.getById(recurringId);
      if (!rec) throw new Error('Recurring template not found');

      const invoiceNumber = await db.invoices.generateInvoiceNumber();
      const nowIso = new Date().toISOString();
      const invDate = rec.nextBillingDate ? `${rec.nextBillingDate}T09:00:00.000Z` : nowIso;

      const newInvoice: Invoice = {
        id: crypto.randomUUID(),
        invoiceNumber,
        date: invDate,
        expenseSourceId: rec.expenseSourceId,
        paymentTypeId: rec.paymentTypeId,
        accountTitleId: rec.accountTitleId,
        purpose: rec.purpose,
        amount: rec.amount,
        amountInWords: numberToWords(rec.amount),
        receivedById: rec.receivedById,
        remarks: `${rec.remarks || ''} [Generated from schedule: ${rec.title}]`.trim(),
        preparedById: rec.preparedById,
        verifiedById: rec.verifiedById || '',
        approvedById: rec.approvedById || '',
        status: 'Submitted',
        sealCode: generateSealCode(),
        referenceCode: generateReferenceCode(),
        createdBy: actorId,
        createdAt: nowIso,
        updatedAt: nowIso,
      };

      await db.invoices.save(newInvoice);

      // Advance schedule
      const nextDate = computeNextBillingDate(rec.frequency, rec.billingDay, new Date(rec.nextBillingDate || Date.now()));
      const updatedRec: RecurringInvoice = {
        ...rec,
        lastGeneratedInvoiceId: newInvoice.id,
        lastGeneratedDate: new Date().toISOString().split('T')[0],
        nextBillingDate: nextDate,
      };
      await db.recurringInvoices.save(updatedRec);

      await db.auditLogs.add(
        actorId, 
        'Generate Recurring Invoice', 
        'Recurring Invoices', 
        newInvoice.id, 
        `Generated invoice ${invoiceNumber} for recurring schedule "${rec.title}" (Amount: ${rec.amount})`
      );

      await db.notifications.add({
        userId: actorId,
        title: 'Recurring Invoice Generated',
        message: `Invoice ${invoiceNumber} for "${rec.title}" has been successfully scheduled and created.`
      });

      return newInvoice;
    }
  },
  auditLogs: {
    getAll: async (): Promise<AuditLog[]> => { await delay(50); return JSON.parse(localStorage.getItem('te_audit_logs') || '[]'); },
    add: async (actorId: string, action: string, module: string, targetId: string, details: string) => {
      const all = await db.auditLogs.getAll();
      const previousLog = all.length > 0 ? all[all.length - 1] : null;
      const previousHash = previousLog?.hash || '0000000000000000000000000000000000000000000000000000000000000000';
      const id = crypto.randomUUID();
      const timestamp = new Date().toISOString();
      const payload = `${id}|${actorId}|${action}|${module}|${targetId}|${details}|${timestamp}|${previousHash}`;
      const hash = await computeHash(payload);
      
      all.push({
        id,
        actorId,
        action,
        module,
        targetId,
        details,
        timestamp,
        hash,
        previousHash
      });
      localStorage.setItem('te_audit_logs', JSON.stringify(all));
    }
  },
  notifications: {
    getAll: async (userId: string): Promise<Notification[]> => { 
      await delay(50); 
      const all: Notification[] = JSON.parse(localStorage.getItem('te_notifications') || '[]'); 
      return all.filter(n => n.userId === userId);
    },
    markAsRead: async (id: string) => {
      const all: Notification[] = JSON.parse(localStorage.getItem('te_notifications') || '[]'); 
      const existing = all.find(n => n.id === id);
      if (existing) existing.read = true;
      localStorage.setItem('te_notifications', JSON.stringify(all));
    },
    add: async (notification: Omit<Notification, 'id' | 'read' | 'createdAt'>) => {
      const all: Notification[] = JSON.parse(localStorage.getItem('te_notifications') || '[]'); 
      all.unshift({
        ...notification,
        id: crypto.randomUUID(),
        read: false,
        createdAt: new Date().toISOString()
      });
      localStorage.setItem('te_notifications', JSON.stringify(all));
    }
  },
  emailLogs: {
    getAll: async (): Promise<EmailLog[]> => {
      await delay(50);
      return JSON.parse(localStorage.getItem('te_email_logs') || '[]');
    },
    getByInvoiceId: async (invoiceId: string): Promise<EmailLog[]> => {
      const all = await db.emailLogs.getAll();
      return all.filter(e => e.invoiceId === invoiceId);
    },
    add: async (log: Omit<EmailLog, 'id' | 'sentAt'>): Promise<EmailLog> => {
      const all = await db.emailLogs.getAll();
      const newLog: EmailLog = {
        ...log,
        id: crypto.randomUUID(),
        sentAt: new Date().toISOString()
      };
      all.unshift(newLog);
      localStorage.setItem('te_email_logs', JSON.stringify(all));

      // Record audit log entry
      await db.auditLogs.add(
        log.senderId || 'sys',
        `Email Sent: ${log.subject}`,
        'Email Service',
        log.invoiceId,
        `Voucher ${log.invoiceNumber} emailed to ${log.recipientEmail} (${log.recipientType}). Msg ID: ${log.messageId}`
      );

      return newLog;
    },
    delete: async (id: string) => {
      const all = await db.emailLogs.getAll();
      localStorage.setItem('te_email_logs', JSON.stringify(all.filter(e => e.id !== id)));
    }
  },
  settings: {
    get: async (): Promise<AppSettings> => { 
      await delay(50); 
      const stored = localStorage.getItem('te_settings');
      if (!stored) return initialSettings;
      return { ...initialSettings, ...JSON.parse(stored) }; 
    },
    save: async (settings: AppSettings) => { 
      localStorage.setItem('te_settings', JSON.stringify(settings)); 
    }
  },
  backup: {
    exportFullBackup: async () => {
      const [users, expenseSources, paymentTypes, accountTitles, people, invoices, recurringInvoices, emailLogs, auditLogs, settings] = await Promise.all([
        db.users.getAll(),
        db.expenseSources.getAll(),
        db.paymentTypes.getAll(),
        db.accountTitles.getAll(),
        db.people.getAll(),
        db.invoices.getAll(),
        db.recurringInvoices.getAll(),
        db.emailLogs.getAll(),
        db.auditLogs.getAll(),
        db.settings.get(),
      ]);

      const backupObject = {
        app: 'Third Eye Enterprise ERP',
        version: '2.4.0',
        exportedAt: new Date().toISOString(),
        data: {
          users,
          expenseSources,
          paymentTypes,
          accountTitles,
          people,
          invoices,
          recurringInvoices,
          emailLogs,
          auditLogs,
          settings,
        }
      };

      // Record backup timestamp in settings
      const updatedSettings = { ...settings, lastBackupDate: new Date().toISOString() };
      await db.settings.save(updatedSettings);

      return backupObject;
    },
    restoreFullBackup: async (backupData: any, actorId: string = 'sys') => {
      if (!backupData || !backupData.data) {
        throw new Error('Invalid backup archive structure');
      }

      const { data } = backupData;
      if (data.users) localStorage.setItem('te_users', JSON.stringify(data.users));
      if (data.expenseSources) localStorage.setItem('te_expense_sources', JSON.stringify(data.expenseSources));
      if (data.paymentTypes) localStorage.setItem('te_payment_types', JSON.stringify(data.paymentTypes));
      if (data.accountTitles) localStorage.setItem('te_account_titles', JSON.stringify(data.accountTitles));
      if (data.people) localStorage.setItem('te_people', JSON.stringify(data.people));
      if (data.invoices) localStorage.setItem('te_invoices', JSON.stringify(data.invoices));
      if (data.recurringInvoices) localStorage.setItem('te_recurring_invoices', JSON.stringify(data.recurringInvoices));
      if (data.emailLogs) localStorage.setItem('te_email_logs', JSON.stringify(data.emailLogs));
      if (data.auditLogs) localStorage.setItem('te_audit_logs', JSON.stringify(data.auditLogs));
      if (data.settings) localStorage.setItem('te_settings', JSON.stringify(data.settings));

      await db.auditLogs.add(
        actorId,
        'System Restore',
        'Backup & Restore',
        'All',
        `Restored full database backup archive created at ${backupData.exportedAt || 'unknown'}`
      );
    }
  }
};

