import React, { useState, useEffect, useRef } from 'react';
import { 
  X, Download, Printer, Palette, Building2, Check, ShieldCheck, 
  Sparkles, RefreshCw, Eye, Sliders, FileText, ChevronRight, CheckCircle2,
  Save, Image as ImageIcon
} from 'lucide-react';
import { Invoice, ExpenseSource, PaymentType, Person, VoucherBrandingSettings } from '../types';
import { formatCurrency } from '../lib/utils';
import { db } from '../lib/db';
import { QRCodeSVG } from 'qrcode.react';
import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';

interface PDFExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  invoice: Invoice;
  expenseSource?: ExpenseSource | null;
  paymentType?: PaymentType | null;
  preparedBy?: Person | null;
  verifiedBy?: Person | null;
  approvedBy?: Person | null;
  receivedBy?: Person | null;
}

const PRESET_COLORS = [
  { name: 'Corporate Blue', hex: '#1e3a8a' },
  { name: 'Deep Navy', hex: '#0f172a' },
  { name: 'Emerald Forest', hex: '#065f46' },
  { name: 'Executive Crimson', hex: '#991b1b' },
  { name: 'Royal Purple', hex: '#581c87' },
  { name: 'Slate Charcoal', hex: '#334155' },
  { name: 'Teal Cyan', hex: '#0f766e' },
  { name: 'Classic Black', hex: '#18181b' },
];

export const PDFExportModal: React.FC<PDFExportModalProps> = ({
  isOpen,
  onClose,
  invoice,
  expenseSource,
  paymentType,
  preparedBy,
  verifiedBy,
  approvedBy,
  receivedBy,
}) => {
  const [activeTab, setActiveTab] = useState<'branding' | 'layout' | 'preview'>('branding');
  const [isExporting, setIsExporting] = useState(false);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  const [branding, setBranding] = useState<VoucherBrandingSettings>({
    companyName: 'Walton Hi-Tech Industries PLC',
    companySubtitle: 'MISCELLANEOUS FUND',
    companyTagline: 'Excellence in Enterprise Financial Governance',
    companyAddress: 'Chandra, Gazipur / Corporate HQ: Plot-1088, Block-I, Sabrina Sobhan Road, Dhaka-1229',
    companyPhone: '+880 9606-555555',
    companyEmail: 'accounts@waltonbd.com',
    companyTaxId: 'BIN: 000129482-0101 / TIN: 719284920194',
    companyWebsite: 'https://waltonbd.com',
    logoInitials: 'MF',
    themeColor: '#1e3a8a',
    templateStyle: 'modern',
    showWatermark: true,
    showQrCode: true,
    showSignatures: true,
    showTaxBin: true,
    showReviewNotes: true,
    footerTerms: 'This expenditure voucher is an authorized financial document generated by Third Eye ERP. Retain for tax audit & verification.'
  });

  const previewVoucherRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      db.settings.get().then(settings => {
        if (settings && settings.branding) {
          setBranding(settings.branding);
        }
      });
      setSaveStatus(null);
    }
  }, [isOpen]);

  if (!isOpen || !invoice) return null;

  const handleSaveAsDefault = async () => {
    try {
      const currentSettings = await db.settings.get();
      await db.settings.save({
        ...currentSettings,
        branding
      });
      setSaveStatus('Branding configuration saved as default for all vouchers!');
      setTimeout(() => setSaveStatus(null), 4000);
    } catch (e: any) {
      setSaveStatus(`Failed to save settings: ${e.message}`);
    }
  };

  const handleDownloadPDF = async () => {
    if (!previewVoucherRef.current) return;
    setIsExporting(true);
    try {
      const imgData = await toPng(previewVoucherRef.current, {
        quality: 0.98,
        pixelRatio: 2,
        backgroundColor: '#ffffff',
      });

      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const img = new Image();
      img.src = imgData;
      await new Promise(res => { img.onload = res; });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (img.height * pdfWidth) / img.width;

      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`Voucher_${invoice.invoiceNumber}_Branded.pdf`);
    } catch (err: any) {
      console.error('PDF Export Error:', err);
      alert('Error generating PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const handlePrint = () => {
    if (!previewVoucherRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to print voucher.');
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Print Voucher - ${invoice.invoiceNumber}</title>
          <style>
            @page { size: A4 portrait; margin: 15mm; }
            body { font-family: 'Arial', sans-serif; color: #111827; margin: 0; padding: 0; background: #fff; }
            table { width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid #111827; padding: 8px; }
            .no-print { display: none; }
          </style>
        </head>
        <body>
          ${previewVoucherRef.current.outerHTML}
          <script>
            window.onload = function() {
              window.print();
              window.onafterprint = function() { window.close(); }
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 sm:p-6 overflow-y-auto animate-in fade-in duration-200">
      <div className="bg-bg-panel border border-border-subtle rounded-2xl w-full max-w-6xl shadow-2xl flex flex-col max-h-[92vh] overflow-hidden my-auto">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border-subtle bg-bg-base">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-accent-100 dark:bg-accent-950 text-accent-700 dark:text-accent-300 flex items-center justify-center border border-accent-200">
              <Palette className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-text-base flex items-center gap-2">
                Customizable PDF Voucher Export
                <span className="text-xs px-2 py-0.5 rounded-full bg-accent-100 text-accent-800 font-mono font-medium">
                  {invoice.invoiceNumber}
                </span>
              </h2>
              <p className="text-xs text-text-muted">Personalize corporate branding, colors, layout templates, and signature blocks</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="p-2 text-text-muted hover:text-text-base hover:bg-bg-panel rounded-xl transition-colors"
              title="Close"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Status Toast */}
        {saveStatus && (
          <div className="mx-6 mt-4 p-3 bg-emerald-50 text-emerald-800 border border-emerald-200 rounded-xl text-xs font-semibold flex items-center gap-2 animate-in slide-in-from-top-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>{saveStatus}</span>
          </div>
        )}

        {/* Main Content Body */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden">
          {/* Left Column: Customization Controls (lg:col-span-5) */}
          <div className="lg:col-span-5 border-r border-border-subtle flex flex-col max-h-[75vh] overflow-y-auto p-5 space-y-6 bg-bg-panel">
            {/* Control Tabs */}
            <div className="flex bg-bg-base p-1 rounded-xl border border-border-subtle">
              <button
                onClick={() => setActiveTab('branding')}
                className={`flex-1 py-1.5 px-3 rounded-lg text-xs font-semibold transition-all ${
                  activeTab === 'branding' 
                    ? 'bg-bg-panel text-text-base shadow-2xs' 
                    : 'text-text-muted hover:text-text-base'
                }`}
              >
                1. Company Branding
              </button>
              <button
                onClick={() => setActiveTab('layout')}
                className={`flex-1 py-1.5 px-3 rounded-lg text-xs font-semibold transition-all ${
                  activeTab === 'layout' 
                    ? 'bg-bg-panel text-text-base shadow-2xs' 
                    : 'text-text-muted hover:text-text-base'
                }`}
              >
                2. Style & Toggles
              </button>
            </div>

            {/* TAB 1: Company Branding */}
            {activeTab === 'branding' && (
              <div className="space-y-4 text-xs">
                <div>
                  <label className="block font-semibold text-text-base mb-1">Company / Organization Name</label>
                  <input
                    type="text"
                    value={branding.companyName}
                    onChange={e => setBranding({ ...branding, companyName: e.target.value })}
                    className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs focus:ring-2 focus:ring-accent-500 focus:border-transparent"
                    placeholder="e.g. Walton Hi-Tech Industries PLC"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Header Subtitle</label>
                    <input
                      type="text"
                      value={branding.companySubtitle || ''}
                      onChange={e => setBranding({ ...branding, companySubtitle: e.target.value })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs"
                      placeholder="e.g. MISCELLANEOUS FUND ACCOUNTS"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Logo Initials</label>
                    <input
                      type="text"
                      maxLength={4}
                      value={branding.logoInitials || ''}
                      onChange={e => setBranding({ ...branding, logoInitials: e.target.value.toUpperCase() })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs uppercase text-center font-bold font-mono"
                      placeholder="e.g. W"
                    />
                  </div>
                </div>

                <div>
                  <label className="block font-semibold text-text-base mb-1">Corporate Address</label>
                  <textarea
                    rows={2}
                    value={branding.companyAddress}
                    onChange={e => setBranding({ ...branding, companyAddress: e.target.value })}
                    className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs resize-none"
                    placeholder="Full facility address or corporate headquarters..."
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Tax / BIN / TIN No.</label>
                    <input
                      type="text"
                      value={branding.companyTaxId || ''}
                      onChange={e => setBranding({ ...branding, companyTaxId: e.target.value })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs"
                      placeholder="BIN: 001928374-0101"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Phone / Helpline</label>
                    <input
                      type="text"
                      value={branding.companyPhone || ''}
                      onChange={e => setBranding({ ...branding, companyPhone: e.target.value })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs"
                      placeholder="+880 9606-555555"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Official Email</label>
                    <input
                      type="email"
                      value={branding.companyEmail || ''}
                      onChange={e => setBranding({ ...branding, companyEmail: e.target.value })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs"
                      placeholder="accounts@company.com"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-text-base mb-1">Website URL</label>
                    <input
                      type="text"
                      value={branding.companyWebsite || ''}
                      onChange={e => setBranding({ ...branding, companyWebsite: e.target.value })}
                      className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs"
                      placeholder="https://company.com"
                    />
                  </div>
                </div>

                {/* Theme Accent Color */}
                <div>
                  <label className="block font-semibold text-text-base mb-1.5">Brand Accent Color</label>
                  <div className="flex flex-wrap gap-2 items-center">
                    {PRESET_COLORS.map(c => (
                      <button
                        key={c.hex}
                        type="button"
                        onClick={() => setBranding({ ...branding, themeColor: c.hex })}
                        className={`w-7 h-7 rounded-full border-2 transition-transform ${
                          branding.themeColor === c.hex ? 'scale-110 border-text-base shadow-sm ring-2 ring-accent-400' : 'border-transparent hover:scale-105'
                        }`}
                        style={{ backgroundColor: c.hex }}
                        title={c.name}
                      />
                    ))}
                    <div className="flex items-center gap-1.5 ml-2">
                      <input
                        type="color"
                        value={branding.themeColor}
                        onChange={e => setBranding({ ...branding, themeColor: e.target.value })}
                        className="w-7 h-7 rounded-md cursor-pointer border border-border-subtle bg-transparent"
                      />
                      <span className="text-[11px] font-mono text-text-muted">{branding.themeColor}</span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* TAB 2: Style & Layout Toggles */}
            {activeTab === 'layout' && (
              <div className="space-y-5 text-xs">
                {/* Template Style Selector */}
                <div>
                  <label className="block font-semibold text-text-base mb-2">Voucher Layout Style</label>
                  <div className="grid grid-cols-2 gap-2.5">
                    {[
                      { id: 'modern', name: 'Corporate Modern', desc: 'Sleek accent banner, crisp borders, clean data cards' },
                      { id: 'classic', name: 'Classic Legal', desc: 'Formal boxed grid with double header dividers' },
                      { id: 'executive', name: 'Executive Minimal', desc: 'Light elegant typography and refined table borders' },
                      { id: 'compact', name: 'Compact 1-Page', desc: 'Tight vertical padding for long transaction descriptions' },
                    ].map(style => (
                      <button
                        key={style.id}
                        type="button"
                        onClick={() => setBranding({ ...branding, templateStyle: style.id as any })}
                        className={`p-3 text-left rounded-xl border transition-all ${
                          branding.templateStyle === style.id
                            ? 'border-accent-600 bg-accent-50/40 dark:bg-accent-950/40 ring-1 ring-accent-600'
                            : 'border-border-subtle bg-bg-base hover:bg-bg-panel'
                        }`}
                      >
                        <div className="font-bold text-text-base">{style.name}</div>
                        <div className="text-[11px] text-text-muted mt-0.5">{style.desc}</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Toggle Controls */}
                <div className="space-y-3 pt-2 border-t border-border-subtle">
                  <p className="font-semibold text-text-base">Document Elements & Seals</p>
                  
                  <label className="flex items-center justify-between p-2.5 bg-bg-base rounded-lg border border-border-subtle cursor-pointer hover:bg-bg-panel">
                    <div>
                      <span className="font-semibold text-text-base block">QR Code Verification Stamp</span>
                      <span className="text-[11px] text-text-muted">Digital verification link for mobile scanners</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={branding.showQrCode}
                      onChange={e => setBranding({ ...branding, showQrCode: e.target.checked })}
                      className="w-4 h-4 rounded text-accent-600 focus:ring-accent-500"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 bg-bg-base rounded-lg border border-border-subtle cursor-pointer hover:bg-bg-panel">
                    <div>
                      <span className="font-semibold text-text-base block">Official Status Watermark</span>
                      <span className="text-[11px] text-text-muted">Overlay diagonal APPROVED / PENDING seal</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={branding.showWatermark}
                      onChange={e => setBranding({ ...branding, showWatermark: e.target.checked })}
                      className="w-4 h-4 rounded text-accent-600 focus:ring-accent-500"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 bg-bg-base rounded-lg border border-border-subtle cursor-pointer hover:bg-bg-panel">
                    <div>
                      <span className="font-semibold text-text-base block">Signatory Approval Block</span>
                      <span className="text-[11px] text-text-muted">3-tier Receiver, Verifier & Approver sign lines</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={branding.showSignatures}
                      onChange={e => setBranding({ ...branding, showSignatures: e.target.checked })}
                      className="w-4 h-4 rounded text-accent-600 focus:ring-accent-500"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 bg-bg-base rounded-lg border border-border-subtle cursor-pointer hover:bg-bg-panel">
                    <div>
                      <span className="font-semibold text-text-base block">Tax BIN & Legal ID</span>
                      <span className="text-[11px] text-text-muted">Display tax registration number in header</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={branding.showTaxBin}
                      onChange={e => setBranding({ ...branding, showTaxBin: e.target.checked })}
                      className="w-4 h-4 rounded text-accent-600 focus:ring-accent-500"
                    />
                  </label>
                </div>

                {/* Footer Terms */}
                <div>
                  <label className="block font-semibold text-text-base mb-1">Custom Footer Terms / Legal Disclaimer</label>
                  <textarea
                    rows={2}
                    value={branding.footerTerms || ''}
                    onChange={e => setBranding({ ...branding, footerTerms: e.target.value })}
                    className="w-full px-3 py-2 bg-bg-base border border-border-subtle rounded-lg text-text-base text-xs resize-none"
                    placeholder="Legal declaration or audit policy note..."
                  />
                </div>
              </div>
            )}

            {/* Bottom Action inside left pane */}
            <div className="pt-4 mt-auto border-t border-border-subtle flex flex-col gap-2">
              <button
                type="button"
                onClick={handleSaveAsDefault}
                className="flex items-center justify-center gap-1.5 px-3 py-2 bg-bg-base hover:bg-bg-panel border border-border-subtle text-text-base rounded-xl text-xs font-semibold transition-colors shadow-2xs"
              >
                <Save className="w-4 h-4 text-accent-600" />
                <span>Save Branding as Default</span>
              </button>
            </div>
          </div>

          {/* Right Column: Live High-Fidelity Printable Voucher Preview (lg:col-span-7) */}
          <div className="lg:col-span-7 bg-slate-200 dark:bg-slate-950 p-6 overflow-y-auto max-h-[75vh] flex justify-center items-start">
            {/* The Actual Scaled Printable Document */}
            <div 
              ref={previewVoucherRef}
              className={`w-full max-w-[210mm] min-h-[280mm] bg-white text-slate-900 shadow-2xl relative box-border overflow-hidden select-none ${branding.templateStyle === 'compact' ? 'p-[12mm]' : 'p-[18mm]'}`}
              style={{ 
                fontFamily: branding.templateStyle === 'classic' ? "'Times New Roman', serif" : 
                            branding.templateStyle === 'executive' ? "'Inter', 'Roboto', sans-serif" : 
                            "'Helvetica Neue', Arial, sans-serif" 
              }}
            >
              {/* Top Accent Color Bar (Modern & Compact) */}
              {(branding.templateStyle === 'modern' || branding.templateStyle === 'compact') && (
                <div 
                  className={`w-full mb-6 rounded-t-sm ${branding.templateStyle === 'compact' ? 'h-1.5' : 'h-2.5'}`}
                  style={{ backgroundColor: branding.themeColor }}
                />
              )}

              {/* Header */}
              <div className={`mb-5 flex items-start justify-between gap-4 ${
                branding.templateStyle === 'classic' ? 'border-b-4 border-double pb-5 border-slate-900' : 
                branding.templateStyle === 'executive' ? 'border-b border-slate-200 pb-5' : 
                'border-b-2 pb-5'
              }`} style={branding.templateStyle === 'modern' || branding.templateStyle === 'compact' ? { borderColor: branding.themeColor } : {}}>
                <div className="flex items-start gap-4">
                  <div>
                    <h1 className={`text-xl font-black uppercase tracking-tight text-slate-900 ${
                      branding.templateStyle === 'executive' ? 'font-light tracking-widest' : ''
                    }`}>
                      {branding.companyName}
                    </h1>
                    {branding.companySubtitle && (
                      <p className={`text-xs font-bold text-slate-700 uppercase mt-0.5 ${
                        branding.templateStyle === 'executive' ? 'tracking-widest font-normal' : 'tracking-wider'
                      }`}>
                        {branding.companySubtitle}
                      </p>
                    )}
                    <p className="text-[11px] text-slate-500 leading-tight mt-1 max-w-md">
                      {branding.companyAddress}
                    </p>
                    {(branding.companyPhone || branding.companyEmail || (branding.showTaxBin && branding.companyTaxId)) && (
                      <div className="flex flex-wrap items-center gap-3 text-[10px] text-slate-600 mt-1 font-medium">
                        {branding.companyPhone && <span>Tel: {branding.companyPhone}</span>}
                        {branding.companyEmail && <span>Email: {branding.companyEmail}</span>}
                        {branding.showTaxBin && branding.companyTaxId && (
                          <span className="font-bold text-slate-800">{branding.companyTaxId}</span>
                        )}
                      </div>
                    )}
                  </div>
                </div>

                {/* Right Header: Voucher Title Badge & QR */}
                <div className="flex flex-col items-end shrink-0">
                  <div 
                    className={`px-4 py-1 text-xs uppercase tracking-widest mb-2 text-center ${
                      branding.templateStyle === 'modern' || branding.templateStyle === 'compact' ? 'rounded-sm text-white font-black' : 
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900 text-slate-900 font-bold' : 
                      'border border-slate-300 text-slate-700 font-medium'
                    }`}
                    style={branding.templateStyle === 'modern' || branding.templateStyle === 'compact' ? { backgroundColor: branding.themeColor } : {}}
                  >
                    Expense Voucher
                  </div>
                  {branding.showQrCode && (
                    <div className={`p-1 flex flex-col items-center ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 'border border-slate-300 bg-slate-50 rounded'
                    }`}>
                      <QRCodeSVG value={`https://whiplc.com/verify/${invoice.sealCode || invoice.invoiceNumber}`} size={56} />
                      <span className="text-[8px] font-mono text-slate-500 mt-0.5 tracking-tighter">AUTHENTICATED</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Metadata Info Grid */}
              <div className={`grid grid-cols-2 mb-5 text-xs ${
                branding.templateStyle === 'modern' ? 'gap-4 p-3.5 bg-slate-50 border border-slate-200 rounded-sm' : 
                branding.templateStyle === 'classic' ? 'gap-0 border-2 border-slate-900 [&>div]:p-3 [&>div:first-child]:border-r-2 [&>div:first-child]:border-slate-900' : 
                branding.templateStyle === 'executive' ? 'gap-6 p-1 border-b border-slate-200 pb-4' : 
                'gap-2 p-2 bg-slate-50 border border-slate-200'
              }`}>
                <div className="space-y-1.5">
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Voucher No:</span>
                    <strong className="text-slate-900 font-mono font-bold text-sm">{invoice.invoiceNumber}</strong>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Voucher Date:</span>
                    <span className="text-slate-900">{new Date(invoice.updatedAt || invoice.date).toLocaleString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Prepared By:</span>
                    <span className="text-slate-900 font-medium">{preparedBy?.name || 'Finance Executive'}</span>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Verified By:</span>
                    <span className="text-slate-900 font-medium">{verifiedBy?.name || 'Finance & Accounts'}</span>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Received By:</span>
                    <span className="text-slate-900 font-medium">{receivedBy?.name || 'Authorized Receiver'}</span>
                  </p>
                </div>
                <div className={`space-y-1.5 ${branding.templateStyle === 'modern' || branding.templateStyle === 'compact' ? 'text-right sm:text-left' : ''}`}>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Vendor / Concern:</span>
                    <strong className="text-slate-900">{expenseSource?.name || 'N/A'}</strong>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Payment Category:</span>
                    <span className="text-slate-900">{paymentType?.name || 'General Operations'}</span>
                  </p>
                  <p className="flex items-center">
                    <span className="font-bold text-slate-600 w-28">Approval Status:</span>
                    <span className="uppercase font-bold text-slate-800 text-[11px] px-2 py-0.5 rounded bg-slate-200">
                      {invoice.status}
                    </span>
                  </p>
                </div>
              </div>

              {/* Itemized Table */}
              <table className={`w-full border-collapse mb-5 text-xs text-slate-900 ${
                branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                branding.templateStyle === 'executive' ? '' : 
                'border border-slate-900'
              }`}>
                <thead>
                  <tr style={
                    branding.templateStyle === 'modern' || branding.templateStyle === 'compact' ? { backgroundColor: branding.themeColor, color: '#ffffff' } : 
                    branding.templateStyle === 'executive' ? { backgroundColor: '#f8fafc', color: '#334155' } : 
                    { backgroundColor: '#f1f5f9', color: '#0f172a' }
                  }>
                    <th className={`px-3 py-2 text-center w-12 font-bold uppercase ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b-2 border-slate-300' : 
                      'border border-slate-900'
                    }`}>Sl.</th>
                    <th className={`px-4 py-2 text-left font-bold uppercase ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b-2 border-slate-300' : 
                      'border border-slate-900'
                    }`}>Particulars / Expenditure Description</th>
                    <th className={`px-4 py-2 text-right w-44 font-bold uppercase ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b-2 border-slate-300' : 
                      'border border-slate-900'
                    }`}>Amount (BDT)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className={`px-3 ${branding.templateStyle === 'compact' ? 'py-4' : 'py-10'} text-center align-top font-bold ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b border-slate-200' : 
                      'border border-slate-900'
                    }`}>1</td>
                    <td className={`px-4 ${branding.templateStyle === 'compact' ? 'py-4' : 'py-10'} align-top ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b border-slate-200' : 
                      'border border-slate-900'
                    }`}>
                      <p className="font-bold text-sm text-slate-900 mb-1">{invoice.purpose}</p>
                      {invoice.remarks && (
                        <p className="text-slate-600 text-xs mt-1">Note: {invoice.remarks}</p>
                      )}
                      {branding.showReviewNotes && invoice.reviewRemarks && (
                        <p className="text-emerald-800 text-xs italic mt-2 bg-emerald-50 p-2 border border-emerald-200 rounded">
                          Review Verification: {invoice.reviewRemarks}
                        </p>
                      )}
                    </td>
                    <td className={`px-4 ${branding.templateStyle === 'compact' ? 'py-4' : 'py-10'} text-right align-top font-bold text-base ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b border-slate-200' : 
                      'border border-slate-900'
                    }`}>
                      {formatCurrency(invoice.amount)}
                    </td>
                  </tr>
                  <tr className="bg-slate-100 font-bold">
                    <td colSpan={2} className={`px-4 py-2.5 text-right uppercase tracking-wider text-xs ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b-2 border-slate-400' : 
                      'border border-slate-900'
                    }`}>
                      Grand Total Payable:
                    </td>
                    <td className={`px-4 py-2.5 text-right font-black text-base text-slate-900 ${
                      branding.templateStyle === 'classic' ? 'border-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-b-2 border-slate-400' : 
                      'border border-slate-900'
                    }`}>
                      {formatCurrency(invoice.amount)}
                    </td>
                  </tr>
                </tbody>
              </table>

              {/* Amount In Words */}
              <div className={`mb-6 p-3 text-xs text-slate-900 ${
                branding.templateStyle === 'classic' ? 'border-2 border-slate-900 bg-slate-50' : 
                branding.templateStyle === 'executive' ? 'border-l-4 border-slate-400 pl-4 bg-slate-50/50' : 
                'border border-slate-900 bg-slate-50'
              }`}>
                <span className="font-bold uppercase tracking-wider text-slate-700 mr-2">Amount in Words:</span>
                <span className="font-semibold italic">{invoice.amountInWords || 'Amount in BDT'} Only.</span>
              </div>

              {/* Signatures Section */}
              {branding.showSignatures && (
                <div className={`mt-16 flex justify-end ${branding.templateStyle === 'compact' ? 'mb-2' : 'mb-6'}`}>
                  <div className="w-1/3 text-xs text-center text-slate-900">
                    <div className={`pt-2 mb-1 font-bold ${
                      branding.templateStyle === 'classic' ? 'border-t-2 border-slate-900' : 
                      branding.templateStyle === 'executive' ? 'border-t border-slate-400' : 
                      'border-t-2 border-slate-900'
                    }`}>Authorized Approval</div>
                    <p className="font-semibold">{approvedBy?.name || (invoice.status === 'Approved' ? 'Authorized Officer' : '________________')}</p>
                    <p className="text-[10px] text-slate-500">{approvedBy?.designation || 'Managing Director'}</p>
                  </div>
                </div>
              )}

              {/* Legal Footer Note */}
              {branding.footerTerms && (
                <div className={`mt-6 pt-3 text-[9px] text-slate-500 text-center leading-relaxed ${
                  branding.templateStyle === 'classic' ? 'border-t-2 border-slate-900' : 
                  branding.templateStyle === 'executive' ? 'border-t border-slate-200' : 
                  'border-t border-slate-200'
                }`}>
                  {branding.footerTerms}
                </div>
              )}

              {/* Seal & Audit Bar */}
              <div className="mt-3 pt-2 border-t border-slate-200 text-[9px] text-slate-400 flex justify-between font-mono">
                <span>SEAL: {invoice.sealCode}</span>
                <span>REF: {invoice.referenceCode}</span>
                <span>GENERATED: {new Date().toLocaleString()}</span>
              </div>

              {/* Watermark Overlay */}
              {branding.showWatermark && (
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.06] pointer-events-none -rotate-45 z-0">
                  <span className="text-[120px] font-black tracking-widest border-[12px] border-slate-900 text-slate-900 px-12 py-4 rounded-2xl uppercase">
                    {invoice.status}
                  </span>
                </div>
              )}
            </div>
          </div>
        </div>
        {/* Modal Footer Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-border-subtle bg-bg-base">
          <div className="flex items-center gap-2 text-xs text-text-muted">
            <Sparkles className="w-4 h-4 text-accent-600" />
            <span>High-resolution 300 DPI Vector PDF output</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 bg-bg-panel hover:bg-bg-base border border-border-subtle text-text-base rounded-xl text-xs font-semibold transition-colors shadow-2xs"
            >
              <Printer className="w-4 h-4 text-text-muted" />
              <span>Direct Print</span>
            </button>

            <button
              onClick={handleDownloadPDF}
              disabled={isExporting}
              className="flex items-center gap-2 px-5 py-2.5 bg-accent-600 hover:bg-accent-700 text-white rounded-xl text-xs font-bold transition-all shadow-sm disabled:opacity-50"
            >
              {isExporting ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Generating PDF...</span>
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  <span>Download Branded PDF</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
